project:
  type: website
  output-dir: docs

website:
  title: "Sarah L. Kiefer"
  navbar:
    search: false
    right:
      - text: About
        href: index.qmd
      - text: CV
        href: cv.qmd
        
format:
  html:
    theme: minty
    toc: false
    html-head:
      - '<meta name="google-site-verification" content="pPa26qgtHmOoxes3DDH8_fUVqT1qfCMwwQ7x3b05x6Y" />'