project:
  type: website
  output-dir: docs

website:
  title: "Sarah L. Kiefer"
  navbar:
    search: false
    right:
      - text: About
        href: index.qmd
      - text: CV
        href: cv.pdf
        
format:
  html:
    theme: minty
    toc: false
